version: ~> 1.0 # needed for imports
import: scala/scala-dev:travis/default.yml

language: scala
env: ADOPTOPENJDK=8
scala:
  - 2.12
  - 2.12.next
  - 2.13
script: sbt test

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    - stage: release
      script: sbt ci-release

notifications:
  email:
    on_success: never
